
  aEventChapter03ClaudTailtiuSpawn ; 9D/8CD6

    PLAY_SONG $51
    YIELD

    RUN_EVENT_CONDITION
      REGISTER_CHARACTER_MAP_SPRITE Tailtiu

    RUN_EVENT_CONDITION
      REGISTER_CHARACTER_MAP_SPRITE Claud

    MAP_SCROLL [1, 9], 4
    YIELD

    PAUSE 20
    YIELD

    LOAD_UNIT_DIRECT Tailtiu, FS_Player, [7, 16], [8, 17], 4, MAP_SPRITE_BLUE
    WAIT_UNIT_SPRITE_DECOMPRESSED

    PAUSE 16
    YIELD

    LOAD_UNIT_DIRECT Claud, FS_Player, [7, 16], [7, 17], 4, MAP_SPRITE_BLUE
    WAIT_UNIT_SPRITE_DECOMPRESSED

    WAIT_UNTIL_MAP_SPRITES_HALTING
    YIELD

    DIALOGUE dialogueChapter03ClaudTailtiuSpawn
    YIELD

    RUN_EVENT_CONDITION
      SET_TALK_TARGET Claud, Sigurd

    PLAY_SFX_WORD $00E0
    PAUSE 35
    YIELD

    RESTORE_PHASE_MUSIC
    YIELD

    END_EVENT
