
  ; Any competent looking lib files come from Zane Avernathy's FE5 standard library folder VOLTEDGE
  ; https://github.com/ZaneAvernathy/VoltEdge

  .include "SAFEGUARD/Events.h"
  .include "SAFEGUARD/Functions.h"

  .include "SAFEGUARD/ActiveSpriteEngine.h"
  .include "SAFEGUARD/AI.h"
  .include "SAFEGUARD/Battle.h"
  .include "SAFEGUARD/Chapters.h"
  .include "SAFEGUARD/Characters.h"
  .include "SAFEGUARD/Classes.h"
  .include "SAFEGUARD/Decompressor.h"
  .include "SAFEGUARD/Deployment.h"
  .include "SAFEGUARD/Dialogue.h"
  .include "SAFEGUARD/DMA.h"
  .include "SAFEGUARD/HDMA.h"
  .include "SAFEGUARD/IORegisters.h"
  .include "SAFEGUARD/Items.h"
  .include "SAFEGUARD/LibraryHelpers.h"
  .include "SAFEGUARD/Menus.h"
  .include "SAFEGUARD/MenuText.h"
  .include "SAFEGUARD/Palettes.h"
  .include "SAFEGUARD/PermanentFlags.h"
  .include "SAFEGUARD/Procs.h"
  .include "SAFEGUARD/RAMStructs.h"
  .include "SAFEGUARD/Save.h"
  .include "SAFEGUARD/Skills.h"
  .include "SAFEGUARD/Sprites.h"
  .include "SAFEGUARD/SRAM.h"
  .include "SAFEGUARD/Terrain.h"
  .include "SAFEGUARD/Tiles.h"
  .include "SAFEGUARD/WRAM.h"
