
  SkillIDDummy      = $00
  SkillIDCanto      = $01
  SkillIDPavise     = $02
  SkillIDWrath      = $03
  SkillIDPursuit    = $04
  SkillIDAdept      = $05
  SkillIDSteal      = $06
  SkillIDUnknown2   = $07 ; valid class skill
  SkillIDDance      = $08
  SkillIDUnknown3   = $09 ; valid class skill
  SkillIDUnknown4   = $0A ; valid class and item skill
  SkillIDDismount   = $0B
  SkillIDCharm      = $0C
  SkillIDPoW        = $0D
  SkillIDNihil      = $0E
  SkillIDMiracle    = $0F
  SkillIDCritical   = $10
  SkillIDVantage    = $11
  SkillIDAccost     = $12
  SkillIDAstra      = $13
  SkillIDLuna       = $14
  SkillIDSol        = $15
  SkillIDHoly       = $16
  SkillIDDarkness   = $17
  SkillIDRenewal    = $18
  SkillIDParagon    = $19
  SkillIDEscape     = $1A
  SkillIDRecover    = $1B
  SkillIDBargain    = $1C
  SkillIDReturn     = $1D
