
  aEventChapter01ElliotRetreats ; 90/8C64

    RESTORE_PHASE_MUSIC
    YIELD

    PAUSE 20
    YIELD

    FILL_EVENT_UNIT_SLOT ElliotCh01, EventUnitSlot1
    MOVE_TEMPORARY_TO_COORDS ElliotCh01, [-1, -1], [16, 0], 4, EventUnitSlot1, MAP_SPRITE_RED, true
    WAIT_UNIT_SPRITE_DECOMPRESSED

    WAIT_UNIT_SPRITE_DECOMPRESSED

    RUN_EVENT_CONDITION
      REMOVE_UNIT ElliotCh01

    WAIT_UNTIL_MAP_SPRITES_HALTING
    YIELD

    END_EVENT
