
  aEventChapter04Ending ; 8E/99C5

    PLAY_SFX_WORD $00E0
    PAUSE 35
    YIELD

    PLAY_SONG $76
    YIELD

    DIALOGUE_WITH_BG dialogueChapter04Ending, DIALOGUE_BG_THRONE, 3, 2
    SET_CAMERA_POSITION [48, 38]
    YIELD

    RUN_EVENT_CONDITION
      ADD_CASTLE_MONEY

    RUN_EVENT_CONDITION
      REMOVE_CHAPTER_STRUCT Chapter04

    RUN_EVENT_CONDITION
      SAVE_CHAPTER_TURNCOUNT

    END_EVENT
