
  aEventChapter07AedSeized ; B2/8B41

    PLAY_SFX_WORD $00E0
    PAUSE 35
    YIELD

    PLAY_SONG $86
    YIELD

    FADE_OUT_BY_TIMER 2
    YIELD

    RUN_EVENT_CONDITION
      UPDATE_LOCATION_AND_MAP_CHANGE_EVENTS

    DIALOGUE_WITH_BG dialogueChapter07AedSeized, DIALOGUE_BG_HALLWAY, 3, 3
    SET_CAMERA_POSITION [13, 0]
    YIELD

    FILL_EVENT_UNIT_SLOT Seliph, EventUnitSlot1
    SET_CAMERA_TO_EVENT_UNIT_SLOT_1

    RUN_EVENT_CONDITION
      SET_TALK_TARGET_IF_UNMARRIED [Patty, Daisy], [Seliph, Seliph]

    PLAY_SFX_WORD $00E0
    PAUSE 35
    YIELD

    RESTORE_PHASE_MUSIC
    YIELD

    END_EVENT
