
  aEventChapter05VelthomerSeized ; 9D/CA8E

    RUN_EVENT_CONDITION
      REMOVE_CHAPTER_STRUCT Chapter05

    RUN_EVENT_CONDITION
      SET_PERMANENT_FLAG PermanentFlag36

    RUN_EVENT_CONDITION
      SAVE_CHAPTER_TURNCOUNT

    END_EVENT
