
  aEventChapter05PhinoraSpawn ; 9D/C1BA

    RUN_EVENT_CONDITION
      REGISTER_UNITGROUP_MAP_SPRITES UNITGroupChapter05Phinora

    PLAY_SFX_WORD $00E0
    PAUSE 35
    YIELD

    PLAY_SONG $74
    YIELD

    MAP_SCROLL [15, 33], 4
    YIELD

    CASTLE_NAME dialogueCastleNameVelthomer, CASLTE_NAME_RED, 90
    YIELD

    DIALOGUE_WITH_BG dialogueChapter05PhinoraSpawn1, DIALOGUE_BG_HALLWAY, 3, 3
    YIELD

    PAUSE 20
    YIELD

    MAP_SCROLL [34, 18], 4
    YIELD

    CASTLE_NAME dialogueCastleNamePhinora, CASLTE_NAME_RED, 90
    YIELD

    DIALOGUE_WITH_BG dialogueChapter05PhinoraSpawn2, DIALOGUE_BG_HALLWAY, 3, 1
    YIELD

    LOAD_UNIT_BY_GROUP UNITGroupChapter05Phinora, aUNITGroupDataChapter05Phinora.ID_02, [42, 26], 4, MAP_SPRITE_RED
    WAIT_UNIT_SPRITE_DECOMPRESSED

    LOAD_UNIT_BY_GROUP UNITGroupChapter05Phinora, aUNITGroupDataChapter05Phinora.ID_03, [42, 26], 4, MAP_SPRITE_RED
    WAIT_UNIT_SPRITE_DECOMPRESSED

    LOAD_UNIT_BY_GROUP UNITGroupChapter05Phinora, aUNITGroupDataChapter05Phinora.ID_04, [42, 26], 4, MAP_SPRITE_RED
    WAIT_UNIT_SPRITE_DECOMPRESSED

    WAIT_UNTIL_MAP_SPRITES_HALTING
    YIELD

    LOAD_UNIT_BY_GROUP UNITGroupChapter05Phinora, aUNITGroupDataChapter05Phinora.ID_01, [42, 24], 4, MAP_SPRITE_RED
    WAIT_UNIT_SPRITE_DECOMPRESSED

    WAIT_UNTIL_MAP_SPRITES_HALTING
    YIELD

    RUN_EVENT_CONDITION
      DEPLOY_UNIT_GROUP UNITGroupChapter05Phinora

    PLAY_SFX_WORD $00E0
    PAUSE 35
    YIELD

    RESTORE_PHASE_MUSIC
    YIELD

    END_EVENT
