  Cavalier       .byte $01
  LanceKnight    .byte $01
  BowKnight      .byte $01
  AxeKnight      .byte $01
  FreeKnight     .byte $01
  Troubadour     .byte $01
  KnightLord     .byte $01
  DukeKnight     .byte $01
  MasterKnight   .byte $01
  Paladin        .byte $01
  PaladinF       .byte $01
  ArchKnight     .byte $01
  Ranger         .byte $01
  MageKnight     .byte $01
  GreatKnight    .byte $01
  PegasusRider   .byte $02
  PegasusKnight  .byte $02
  FalconKnight   .byte $02
  Dragonrider    .byte $06
  Dragonknight   .byte $06
  Dragonmaster   .byte $06
  Archer         .byte $00
  Myrmidon       .byte $00
  Swordmaster    .byte $00
  Sniper         .byte $00
  Hero           .byte $00
  General        .byte $08
  Emperor        .byte $08
  Baron          .byte $08
  Soldier        .byte $00
  SpearSoldier   .byte $00
  AxeSoldier     .byte $00
  BowSoldier     .byte $00
  SwordSoldier   .byte $00
  LanceArmor     .byte $08
  AxeArmor       .byte $08
  BowArmor       .byte $08
  SwordArmor     .byte $08
  Barbarian      .byte $00
  Fighter        .byte $00
  Brigand        .byte $00
  Warrior        .byte $00
  Hunter         .byte $00
  Pirate         .byte $00
  JuniorLord     .byte $00
  WarMage        .byte $10
  Prince         .byte $00
  Princess       .byte $00
  WarMageF       .byte $10
  Queen          .byte $00
  Dancer         .byte $00
  Priest         .byte $00
  Mage           .byte $10
  FireMage       .byte $10
  ThunderMage    .byte $10
  WindMage       .byte $10
  HighPriest     .byte $10
  Bishop         .byte $10
  Sage           .byte $10
  Bard           .byte $00
  Priestess      .byte $00
  DarkMage       .byte $10
  DarkBishop     .byte $10
  Thief          .byte $00
  Rogue          .byte $00
  Civilian       .byte $00
  Child          .byte $00
  Ballista       .byte $00
  IronBallista   .byte $00
  KillerBallista .byte $00
  GreatBallista  .byte $00
  DarkPrince     .byte $00