
  Sigurd    .byte $FF
  Naoise    .byte Paladin
  Alec      .byte Paladin
  Arden     .byte General
  Finn      .byte DukeKnight
  Quan      .byte $FF
  Midayle   .byte ArchKnight
  Lewyn     .byte Sage
  Chulainn  .byte Hero
  Azelle    .byte MageKnight
  Jamke     .byte Sniper
  Claud     .byte $FF
  Beowulf   .byte Ranger
  Lex       .byte GreatKnight
  Dew       .byte Rogue
  Deirdre   .byte $FF
  Ethlyn    .byte PaladinF
  Lachesis  .byte MasterKnight
  Ayra      .byte Swordmaster
  Erinys    .byte FalconKnight
  Tailtiu   .byte WarMageF
  Silvia    .byte $FF
  Edainn    .byte HighPriest
  Brigid    .byte $FF
  Seliph    .byte KnightLord
  Shannan   .byte $FF
  Dalvin    .byte Hero
  Asaello   .byte Sniper
  Leif      .byte MasterKnight
  Iuchar    .byte GreatKnight
  Charlot   .byte HighPriest
  Hawk      .byte $FF
  Tristan   .byte Ranger
  OldFinn   .byte DukeKnight
  Deimne    .byte ArchKnight
  Hannibal  .byte $FF
  Ares      .byte Paladin
  Amid      .byte WarMage
  Oifey     .byte Paladin
  Daisy     .byte Rogue
  Creidne   .byte Hero
  Muirne    .byte HighPriest
  Julia     .byte Sage
  Altena    .byte Dragonmaster
  Hermina   .byte FalconKnight
  Linda     .byte WarMageF
  Laylea    .byte $FF
  Jeanne    .byte PaladinF
  Iucharba  .byte Warrior
  Scathach  .byte Hero
  Febail    .byte Sniper
  Coirpre   .byte HighPriest
  Ced       .byte $FF
  Diarmuid  .byte Ranger
  Lester    .byte ArchKnight
  Arthur    .byte MageKnight
  Patty     .byte Rogue
  Larcei    .byte Swordmaster
  Lana      .byte HighPriest
  Fee       .byte FalconKnight
  Tine      .byte WarMageF
  Lene      .byte $FF
  Nanna     .byte PaladinF