
  Sigurd    .byte $FF
  Naoise    .byte PaladinClass
  Alec      .byte PaladinClass
  Arden     .byte GeneralClass
  Finn      .byte DukeKnightClass
  Quan      .byte $FF
  Midayle   .byte ArchKnightClass
  Lewyn     .byte SageClass
  Chulainn  .byte HeroClass
  Azelle    .byte MageKnightClass
  Jamke     .byte SniperClass
  Claud     .byte $FF
  Beowulf   .byte RangerClass
  Lex       .byte GreatKnightClass
  Dew       .byte RogueClass
  Deirdre   .byte $FF
  Ethlyn    .byte PaladinFClass
  Lachesis  .byte MasterKnightClass
  Ayra      .byte SwordmasterClass
  Erinys    .byte FalconKnightClass
  Tailtiu   .byte WarMageFClass
  Silvia    .byte $FF
  Edainn    .byte HighPriestClass
  Brigid    .byte $FF
  Seliph    .byte KnightLordClass
  Shannan   .byte $FF
  Dalvin    .byte HeroClass
  Asaello   .byte SniperClass
  Leif      .byte MasterKnightClass
  Iuchar    .byte GreatKnightClass
  Charlot   .byte HighPriestClass
  Hawk      .byte $FF
  Tristan   .byte RangerClass
  OldFinn   .byte DukeKnightClass
  Deimne    .byte ArchKnightClass
  Hannibal  .byte $FF
  Ares      .byte PaladinClass
  Amid      .byte WarMageClass
  Oifey     .byte PaladinClass
  Daisy     .byte RogueClass
  Creidne   .byte HeroClass
  Muirne    .byte HighPriestClass
  Julia     .byte SageClass
  Altena    .byte DragonmasterClass
  Hermina   .byte FalconKnightClass
  Linda     .byte WarMageFClass
  Laylea    .byte $FF
  Jeanne    .byte PaladinFClass
  Iucharba  .byte WarriorClass
  Scathach  .byte HeroClass
  Febail    .byte SniperClass
  Coirpre   .byte HighPriestClass
  Ced       .byte $FF
  Diarmuid  .byte RangerClass
  Lester    .byte ArchKnightClass
  Arthur    .byte MageKnightClass
  Patty     .byte RogueClass
  Larcei    .byte SwordmasterClass
  Lana      .byte HighPriestClass
  Fee       .byte FalconKnightClass
  Tine      .byte WarMageFClass
  Lene      .byte $FF
  Nanna     .byte PaladinFClass