  Cavalier       .byte CavalierEffectiveness
  LanceKnight    .byte CavalierEffectiveness
  BowKnight      .byte CavalierEffectiveness
  AxeKnight      .byte CavalierEffectiveness
  FreeKnight     .byte CavalierEffectiveness
  Troubadour     .byte CavalierEffectiveness
  KnightLord     .byte CavalierEffectiveness
  DukeKnight     .byte CavalierEffectiveness
  MasterKnight   .byte CavalierEffectiveness
  Paladin        .byte CavalierEffectiveness
  PaladinF       .byte CavalierEffectiveness
  ArchKnight     .byte CavalierEffectiveness
  Ranger         .byte CavalierEffectiveness
  MageKnight     .byte CavalierEffectiveness
  GreatKnight    .byte CavalierEffectiveness
  PegasusRider   .byte FlierEffectiveness
  PegasusKnight  .byte FlierEffectiveness
  FalconKnight   .byte FlierEffectiveness
  Dragonrider    .byte (FlierEffectiveness | DragonEffectiveness)
  Dragonknight   .byte (FlierEffectiveness | DragonEffectiveness)
  Dragonmaster   .byte (FlierEffectiveness | DragonEffectiveness)
  Archer         .byte None
  Myrmidon       .byte None
  Swordmaster    .byte None
  Sniper         .byte None
  Hero           .byte None
  General        .byte ArmorEffectiveness
  Emperor        .byte ArmorEffectiveness
  Baron          .byte ArmorEffectiveness
  Soldier        .byte None
  SpearSoldier   .byte None
  AxeSoldier     .byte None
  BowSoldier     .byte None
  SwordSoldier   .byte None
  LanceArmor     .byte ArmorEffectiveness
  AxeArmor       .byte ArmorEffectiveness
  BowArmor       .byte ArmorEffectiveness
  SwordArmor     .byte ArmorEffectiveness
  Barbarian      .byte None
  Fighter        .byte None
  Brigand        .byte None
  Warrior        .byte None
  Hunter         .byte None
  Pirate         .byte None
  JuniorLord     .byte None
  WarMage        .byte MageEffectiveness
  Prince         .byte None
  Princess       .byte None
  WarMageF       .byte MageEffectiveness
  Queen          .byte None
  Dancer         .byte None
  Priest         .byte None
  Mage           .byte MageEffectiveness
  FireMage       .byte MageEffectiveness
  ThunderMage    .byte MageEffectiveness
  WindMage       .byte MageEffectiveness
  HighPriest     .byte MageEffectiveness
  Bishop         .byte MageEffectiveness
  Sage           .byte MageEffectiveness
  Bard           .byte None
  Priestess      .byte None
  DarkMage       .byte MageEffectiveness
  DarkBishop     .byte MageEffectiveness
  Thief          .byte None
  Rogue          .byte None
  Civilian       .byte None
  Child          .byte None
  Ballista       .byte None
  IronBallista   .byte None
  KillerBallista .byte None
  GreatBallista  .byte None
  DarkPrince     .byte None