
  aEventPrologueQuanGroupSpawn ; B1/82E2

    PLAY_SONG $73
    YIELD

    RUN_EVENT_CONDITION
      REGISTER_CHARACTER_MAP_SPRITE Quan

    RUN_EVENT_CONDITION
      REGISTER_CHARACTER_MAP_SPRITE Ethlyn

    RUN_EVENT_CONDITION
      REGISTER_CHARACTER_MAP_SPRITE Finn

    PAUSE 10
    YIELD

    MAP_SCROLL [48, 6], 4
    YIELD

    PAUSE 10
    YIELD

    LOAD_UNIT_DIRECT Quan, FS_Player, [63, 13], [59, 14], 4, MAP_SPRITE_BLUE
    WAIT_UNIT_SPRITE_DECOMPRESSED
    PAUSE 4
    YIELD

    LOAD_UNIT_DIRECT Finn, FS_Player, [63, 13], [60, 14], 4, MAP_SPRITE_BLUE
    WAIT_UNIT_SPRITE_DECOMPRESSED
    PAUSE 4
    YIELD

    LOAD_UNIT_DIRECT Ethlyn, FS_Player, [63, 13], [61, 14], 4, MAP_SPRITE_BLUE
    WAIT_UNIT_SPRITE_DECOMPRESSED
    WAIT_UNTIL_MAP_SPRITES_HALTING
    YIELD

    DIALOGUE dialogueChapterPrologueQuanGroupSpawn
    YIELD

    RUN_EVENT_CONDITION
      SET_TALK_TARGET Ethlyn, Sigurd

    RUN_EVENT_CONDITION
      SET_TALK_TARGET Quan, Sigurd

    PLAY_SFX_WORD $00E0
    PAUSE 35
    YIELD

    RESTORE_PHASE_MUSIC
    YIELD

    END_EVENT
