
  aEventPrologueYngviSeized ; B1/839E

    PLAY_SFX_WORD $00E0
    PAUSE 35
    YIELD

    PLAY_SONG $73
    YIELD

    RUN_EVENT_CONDITION
      REGISTER_CHARACTER_MAP_SPRITE Midir

    DIALOGUE_WITH_BG dialogueChapterPrologueYngviSeized, DIALOGUE_BG_GATE, 3, 2
    SET_CAMERA_POSITION [26, 17]
    YIELD

    LOAD_UNIT_DIRECT Midir, FS_Player, [33, 25], [33, 25], 4, MAP_SPRITE_BLUE
    WAIT_UNIT_SPRITE_DECOMPRESSED

    WAIT_UNTIL_MAP_SPRITES_HALTING
    YIELD

    FILL_EVENT_UNIT_SLOT Sigurd, EventUnitSlot1
    SET_CAMERA_TO_EVENT_UNIT_SLOT_1

    PLAY_SFX_WORD $00E0
    PAUSE 35
    YIELD

    RESTORE_PHASE_MUSIC
    YIELD

    END_EVENT
