
  aEventChapter02LewynSilviaSpawn ; 8E/81E2

    RUN_EVENT_CONDITION
      REGISTER_CHARACTER_MAP_SPRITE Lewyn

    RUN_EVENT_CONDITION
      REGISTER_CHARACTER_MAP_SPRITE Silvia

    PLAY_SONG $6B
    YIELD

    MAP_SCROLL [32, 17], 4
    YIELD

    PAUSE 25
    YIELD

    DIALOGUE_WITH_BG dialogueChapter02LewynSilviaSpawn, DIALOGUE_BG_FOUNTAIN, 3, 1
    YIELD

    PAUSE 20
    YIELD

    RUN_EVENT_CONDITION
      OPEN_VILLAGE Ch02_Village1

    RUN_EVENT_CONDITION
      UPDATE_LOCATION_AND_MAP_CHANGE_EVENTS

    PAUSE 20
    YIELD

    LOAD_UNIT_DIRECT Lewyn, FS_Player, [40, 24], [39, 25], 4, MAP_SPRITE_BLUE
    WAIT_UNIT_SPRITE_DECOMPRESSED

    LOAD_UNIT_DIRECT Silvia, FS_Player, [40, 24], [40, 25], 4, MAP_SPRITE_BLUE
    WAIT_UNIT_SPRITE_DECOMPRESSED

    WAIT_UNTIL_MAP_SPRITES_HALTING
    YIELD

    RUN_EVENT_CONDITION
      SET_TALK_TARGET Sigurd, Lewyn

    PLAY_SFX_WORD $00E0

    PAUSE 35
    YIELD

    RESTORE_PHASE_MUSIC
    YIELD

    END_EVENT
