
  aEventChapter02ChulainnRecruitmentInfini ; 8E/874D

    RUN_EVENT_CONDITION
      REGISTER_CHARACTER_MAP_SPRITE Chulainn

    PLAY_SFX_WORD $00E0
    PAUSE 35
    YIELD

    PLAY_SONG $73
    YIELD

    DIALOGUE_WITH_BG dialogueChapter02ChulainnRecruitment, DIALOGUE_BG_ALLEY, 3, 1
    YIELD

    LOAD_UNIT_DIRECT Chulainn, FS_Player, [12, 5], [12, 5], 4, MAP_SPRITE_BLUE
    WAIT_UNIT_SPRITE_DECOMPRESSED

    WAIT_UNTIL_MAP_SPRITES_HALTING
    YIELD

    PLAY_SFX_WORD $00E0
    PAUSE 35
    YIELD

    RESTORE_PHASE_MUSIC
    YIELD

    END_EVENT
