
  aEventChapter02InfiniBrigandsSpawn ; 8E/8162

    RUN_EVENT_CONDITION
      REGISTER_UNITGROUP_MAP_SPRITES UNITGroupChapter02Yellows

    PLAY_SFX_WORD $00E0
    PAUSE 35
    YIELD

    PLAY_SONG $2A
    YIELD

    MAP_SCROLL [5, 0], 4
    YIELD

    CASTLE_NAME dialogueCastleNameInfini, CASLTE_NAME_YELLOW, 90
    YIELD

    DIALOGUE_WITH_BG dialogueChapter02InfiniBrigandsSpawn, DIALOGUE_BG_HALLWAY, 3, 1
    YIELD

    LOAD_UNIT_BY_GROUP UNITGroupChapter02Yellows, aUNITGroupDataChapter02Yellows.ID_06, [12, 5], 4, MAP_SPRITE_YELLOW
    WAIT_UNIT_SPRITE_DECOMPRESSED

    PAUSE 12
    YIELD

    LOAD_UNIT_BY_GROUP UNITGroupChapter02Yellows, aUNITGroupDataChapter02Yellows.ID_07, [12, 5], 4, MAP_SPRITE_YELLOW
    WAIT_UNIT_SPRITE_DECOMPRESSED

    PAUSE 12
    YIELD

    LOAD_UNIT_BY_GROUP UNITGroupChapter02Yellows, aUNITGroupDataChapter02Yellows.ID_08, [12, 5], 4, MAP_SPRITE_YELLOW
    WAIT_UNIT_SPRITE_DECOMPRESSED

    PAUSE 12
    YIELD

    LOAD_UNIT_BY_GROUP UNITGroupChapter02Yellows, aUNITGroupDataChapter02Yellows.ID_09, [12, 5], 4, MAP_SPRITE_YELLOW
    WAIT_UNIT_SPRITE_DECOMPRESSED

    WAIT_UNTIL_MAP_SPRITES_HALTING
    YIELD

    RUN_EVENT_CONDITION
      DEPLOY_UNIT_GROUP UNITGroupChapter02Yellows

    END_EVENT
